databases:
 - name: cron_rails_tester
   databaseName: cron_rails_tester
   user: cron_rails_tester

services:
 - type: web
   name: cron_rails_tester
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: CRON_RAILS_TESTER_DB_URL
       fromDatabase:
         name: cron_rails_tester
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false
